use_frameworks!

platform :ios, '10.0'

target 'ZIMKitDemo' do
  pod 'ZIMKit_OC', :path => '../..'
  pod 'Bugly', :configurations => ['Release']
  
  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['CODE_SIGN_IDENTITY'] = ''
           end
      end
    end
  end
  
end
